In [1]:
import seaborn as sns
df=sns.load_dataset("tips")

In [2]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [4]:
X=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
X.head()

    tip     sex smoker  day    time  size
0  1.01  Female     No  Sun  Dinner     2
1  1.66    Male     No  Sun  Dinner     3
2  3.50    Male     No  Sun  Dinner     3
3  3.31    Male     No  Sun  Dinner     2
4  3.61  Female     No  Sun  Dinner     4

In [5]:
y=df[["total_bill"]]
y.head()

   total_bill
0       16.99
1       10.34
2       21.01
3       23.68
4       24.59

In [6]:
df["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=3)

In [8]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

In [9]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

ohe1 = OneHotEncoder(sparse_output=False)
encoded_data = ohe1.fit_transform(X_train[["day"]])
df_encoded = pd.DataFrame(encoded_data, columns=ohe1.get_feature_names_out(["day"]))

df_encoded.reset_index(drop=True, inplace=True)
X_train.reset_index(drop=True, inplace=True)

X_train.drop(labels="day", axis=1, inplace=True)
X_train = pd.concat([df_encoded, X_train], axis=1)

In [10]:
X_train.head()

   day_Fri  day_Sat  day_Sun  day_Thur   tip  sex  smoker  time  size
0      0.0      0.0      1.0       0.0  3.61    0       0     0     4
1      0.0      0.0      0.0       1.0  4.00    1       0     1     4
2      0.0      0.0      1.0       0.0  4.00    1       1     0     3
3      0.0      1.0      0.0       0.0  1.97    1       0     0     2
4      0.0      1.0      0.0       0.0  3.27    1       0     0     2

In [11]:
encoded_data = ohe1.transform(X_test[["day"]]) 
df_encoded = pd.DataFrame(encoded_data, columns=ohe1.get_feature_names_out(["day"]))

df_encoded.reset_index(drop=True, inplace=True)
X_test.reset_index(drop=True, inplace=True)

X_test.drop(labels="day", axis=1, inplace=True)
X_test = pd.concat([df_encoded, X_test], axis=1)

In [12]:
X_test.head()

   day_Fri  day_Sat  day_Sun  day_Thur   tip  sex  smoker  time  size
0      0.0      0.0      1.0       0.0  3.02    0       0     0     2
1      0.0      0.0      0.0       1.0  3.25    0       0     1     2
2      0.0      0.0      0.0       1.0  1.48    1       0     1     2
3      0.0      0.0      1.0       0.0  2.00    1       0     0     2
4      0.0      1.0      0.0       0.0  2.00    1       1     0     2

In [14]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
svr=SVR()
para={
    "kernel":['rbf', 'sigmoid'],
    "C":[1,10,100,1000],
    "gamma":[.0001,.1,.01,.001]
}
grid=GridSearchCV(estimator=svr,param_grid=para,verbose=3,refit=True)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV 1/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.022 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.005 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.233 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.151 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 1/5] END C=1, gamma=0.0001, kernel=sigmoid;, score=-0.025 total time=   0.0s
[CV 2/5] END .C=1, gamma=0.0001, kernel=sigmoid;, score=0.001 total time=   0.0s
[CV 3/5] END C=1, gamma=0.0001, kernel=sigmoid;, score=-0.237 total time=   0.0s
[CV 4/5] END C=1, gamma=0.0001, kernel=sigmoid;, score=-0.155 total time=   0.0s
[CV 5/5] END C=1, gamma=0.0001, kernel=sigmoid;, score=-0.022 total time=   0.0s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.426 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.378 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.301 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.418 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.297 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.774 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.723 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.920 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-1.073 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.557 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.297 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.376 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.154 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.259 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.211 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.182 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.247 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.003 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.101 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.117 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.037 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.071 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.167 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.017 total time=   0.0s
[CV 1/5] END ..C=1, gamma=0.001, kernel=sigmoid;, score=0.005 total time=   0.0s
[CV 2/5] END ..C=1, gamma=0.001, kernel=sigmoid;, score=0.036 total time=   0.0s
[CV 3/5] END .C=1, gamma=0.001, kernel=sigmoid;, score=-0.201 total time=   0.0s
[CV 4/5] END .C=1, gamma=0.001, kernel=sigmoid;, score=-0.121 total time=   0.0s
[CV 5/5] END .C=1, gamma=0.001, kernel=sigmoid;, score=-0.001 total time=   0.0s
[CV 1/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.038 total time=   0.0s
[CV 2/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.073 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.0001, kernel=rbf;, score=-0.166 total time=   0.0s
[CV 4/5] END ...C=10, gamma=0.0001, kernel=rbf;, score=-0.082 total time=   0.0s
[CV 5/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.017 total time=   0.0s
[CV 1/5] END C=10, gamma=0.0001, kernel=sigmoid;, score=0.005 total time=   0.0s
[CV 2/5] END C=10, gamma=0.0001, kernel=sigmoid;, score=0.036 total time=   0.0s
[CV 3/5] END C=10, gamma=0.0001, kernel=sigmoid;, score=-0.201 total time=   0.0s
[CV 4/5] END C=10, gamma=0.0001, kernel=sigmoid;, score=-0.121 total time=   0.0s
[CV 5/5] END C=10, gamma=0.0001, kernel=sigmoid;, score=-0.001 total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.441 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.572 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.529 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.447 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.389 total time=   0.0s
[CV 1/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-30.090 total time=   0.0s
[CV 2/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-24.645 total time=   0.0s
[CV 3/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-23.117 total time=   0.0s
[CV 4/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-37.312 total time=   0.0s
[CV 5/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-22.035 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.466 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.604 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.501 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.416 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.307 total time=   0.0s
[CV 1/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.465 total time=   0.0s
[CV 2/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.591 total time=   0.0s
[CV 3/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.466 total time=   0.0s
[CV 4/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.448 total time=   0.0s
[CV 5/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.312 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.328 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.455 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.218 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.293 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.235 total time=   0.0s
[CV 1/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.207 total time=   0.0s
[CV 2/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.299 total time=   0.0s
[CV 3/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.037 total time=   0.0s
[CV 4/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.144 total time=   0.0s
[CV 5/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.137 total time=   0.0s
[CV 1/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.332 total time=   0.0s
[CV 2/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.461 total time=   0.0s
[CV 3/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.225 total time=   0.0s
[CV 4/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.299 total time=   0.0s
[CV 5/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.237 total time=   0.0s
[CV 1/5] END C=100, gamma=0.0001, kernel=sigmoid;, score=0.207 total time=   0.0s
[CV 2/5] END C=100, gamma=0.0001, kernel=sigmoid;, score=0.300 total time=   0.0s
[CV 3/5] END C=100, gamma=0.0001, kernel=sigmoid;, score=0.037 total time=   0.0s
[CV 4/5] END C=100, gamma=0.0001, kernel=sigmoid;, score=0.144 total time=   0.0s
[CV 5/5] END C=100, gamma=0.0001, kernel=sigmoid;, score=0.137 total time=   0.0s
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.372 total time=   0.0s
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.625 total time=   0.0s
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.516 total time=   0.0s
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.176 total time=   0.0s
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.400 total time=   0.0s
[CV 1/5] END C=100, gamma=0.1, kernel=sigmoid;, score=-2493.525 total time=   0.0s
[CV 2/5] END C=100, gamma=0.1, kernel=sigmoid;, score=-1883.929 total time=   0.0s
[CV 3/5] END C=100, gamma=0.1, kernel=sigmoid;, score=-1723.834 total time=   0.0s
[CV 4/5] END C=100, gamma=0.1, kernel=sigmoid;, score=-3091.580 total time=   0.0s
[CV 5/5] END C=100, gamma=0.1, kernel=sigmoid;, score=-1811.759 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.443 total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.658 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.574 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.349 total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.309 total time=   0.0s
[CV 1/5] END .C=100, gamma=0.01, kernel=sigmoid;, score=0.412 total time=   0.0s
[CV 2/5] END .C=100, gamma=0.01, kernel=sigmoid;, score=0.232 total time=   0.0s
[CV 3/5] END .C=100, gamma=0.01, kernel=sigmoid;, score=0.357 total time=   0.0s
[CV 4/5] END .C=100, gamma=0.01, kernel=sigmoid;, score=0.393 total time=   0.0s
[CV 5/5] END .C=100, gamma=0.01, kernel=sigmoid;, score=0.284 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.472 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.659 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.520 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.399 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.318 total time=   0.0s
[CV 1/5] END C=100, gamma=0.001, kernel=sigmoid;, score=0.454 total time=   0.0s
[CV 2/5] END C=100, gamma=0.001, kernel=sigmoid;, score=0.631 total time=   0.0s
[CV 3/5] END C=100, gamma=0.001, kernel=sigmoid;, score=0.475 total time=   0.0s
[CV 4/5] END C=100, gamma=0.001, kernel=sigmoid;, score=0.436 total time=   0.0s
[CV 5/5] END C=100, gamma=0.001, kernel=sigmoid;, score=0.313 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.473 total time=   0.0s
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.663 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.523 total time=   0.0s
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.403 total time=   0.0s
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.320 total time=   0.0s
[CV 1/5] END C=1000, gamma=0.0001, kernel=sigmoid;, score=0.454 total time=   0.0s
[CV 2/5] END C=1000, gamma=0.0001, kernel=sigmoid;, score=0.632 total time=   0.0s
[CV 3/5] END C=1000, gamma=0.0001, kernel=sigmoid;, score=0.474 total time=   0.0s
[CV 4/5] END C=1000, gamma=0.0001, kernel=sigmoid;, score=0.436 total time=   0.0s
[CV 5/5] END C=1000, gamma=0.0001, kernel=sigmoid;, score=0.313 total time=   0.0s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.010 total time=   0.0s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.535 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.1, kernel=rbf;, score=-0.037 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.1, kernel=rbf;, score=-0.766 total time=   0.0s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.202 total time=   0.0s
[CV 1/5] END C=1000, gamma=0.1, kernel=sigmoid;, score=-246874.087 total time=   0.0s
[CV 2/5] END C=1000, gamma=0.1, kernel=sigmoid;, score=-182198.612 total time=   0.0s
[CV 3/5] END C=1000, gamma=0.1, kernel=sigmoid;, score=-166944.543 total time=   0.0s
[CV 4/5] END C=1000, gamma=0.1, kernel=sigmoid;, score=-305925.354 total time=   0.0s
[CV 5/5] END C=1000, gamma=0.1, kernel=sigmoid;, score=-176870.021 total time=   0.0s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.383 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.688 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.563 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.349 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.296 total time=   0.0s
[CV 1/5] END C=1000, gamma=0.01, kernel=sigmoid;, score=-26.453 total time=   0.0s
[CV 2/5] END C=1000, gamma=0.01, kernel=sigmoid;, score=-139.067 total time=   0.0s
[CV 3/5] END C=1000, gamma=0.01, kernel=sigmoid;, score=-66.936 total time=   0.0s
[CV 4/5] END C=1000, gamma=0.01, kernel=sigmoid;, score=-70.069 total time=   0.0s
[CV 5/5] END C=1000, gamma=0.01, kernel=sigmoid;, score=-10.211 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.445 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.682 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.583 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.336 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.321 total time=   0.0s
[CV 1/5] END C=1000, gamma=0.001, kernel=sigmoid;, score=0.447 total time=   0.0s
[CV 2/5] END C=1000, gamma=0.001, kernel=sigmoid;, score=0.682 total time=   0.0s
[CV 3/5] END C=1000, gamma=0.001, kernel=sigmoid;, score=0.570 total time=   0.0s
[CV 4/5] END C=1000, gamma=0.001, kernel=sigmoid;, score=0.394 total time=   0.0s
[CV 5/5] END C=1000, gamma=0.001, kernel=sigmoid;, score=0.323 total time=   0.0s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [1, 10, 100, 1000],
                         'gamma': [0.0001, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'sigmoid']},
             verbose=3)

In [15]:
grid.best_params_

{'C': 1000, 'gamma': 0.001, 'kernel': 'sigmoid'}

In [17]:
y_pred=grid.predict(X_test)

In [18]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.571914078011561
3.880792320706841