In [3]:
import pandas as pd;
import matplotlib.pyplot as plt;
import warnings;
import numpy as np;

warnings.filterwarnings("ignore");

In [4]:
df=pd.read_csv("https://raw.githubusercontent.com/krishnaik06/playstore-Dataset/main/googleplaystore.csv");

In [5]:
df.info()
df.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [6]:
df.shape

(10841, 13)

In [7]:
df[df["App"].duplicated()].shape

(1181, 13)

In [9]:
df_copy=df.copy()

In [10]:
df_copy=df_copy.drop_duplicates(subset=["App"],keep="first")

In [11]:
df_copy["App"].duplicated().value_counts()

App
False    9660
Name: count, dtype: int64

In [12]:
df_copy.head(1)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up

In [13]:
df_copy["Size"]=df_copy["Size"].str.replace("M","000");

In [14]:
df_copy["Size"]=df_copy["Size"].replace("Varies with device",np.nan);

In [17]:
df_copy["Size"]=df_copy["Size"].str.replace(",","");
df_copy["Size"]=df_copy["Size"].str.replace("+","")
df_copy["Size"]=df_copy["Size"].astype(float)

In [18]:
df_copy[~df_copy["Reviews"].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9300,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,1000.0,Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [19]:
df_copy.reset_index(drop=True, inplace=True)

In [20]:
df_copy.drop(df_copy.index[9300],inplace=True)

In [21]:
df_copy["Reviews"]=df_copy["Reviews"].astype(int)

In [22]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9659 entries, 0 to 9659
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   object
 6   Type            9658 non-null   object
 7   Price           9659 non-null   object
 8   Content Rating  9659 non-null   object
 9   Genres          9659 non-null   object
 10  Last Updated    9659 non-null   object
 11  Current Ver     9651 non-null   object
 12  Android Ver     9657 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 1.0+ MB

In [35]:
df_copy["Installs"]

0          10000
1         500000
2        5000000
3       50000000
4         100000
          ...
9655        5000
9656         100
9657        1000
9658        1000
9659    10000000
Name: Installs, Length: 9659, dtype: object

In [34]:
df_copy["Price"].unique()

array(['0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.00', '29.99',
       '12.99', '2.49', '10.99', '1.50', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.70', '8.99', '2.00', '3.88',
       '25.99', '399.99', '17.99', '400.00', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.50', '1.59', '6.49', '1.29', '5.00', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.90', '8.49',
       '1.75', '14.00', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       '1.20', '1.04'], dtype=object)

In [33]:
col=["Installs","Price"];
to_be_removed=["+",",","$"];
for ch in to_be_removed:
    for cl in col:
        df_copy[cl]=df_copy[cl].str.replace(ch,"");

In [38]:
df_copy["Installs"]=df_copy["Installs"].astype(int);
df_copy["Price"]=df_copy["Price"].astype(float);

In [39]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9659 entries, 0 to 9659
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   int64
 6   Type            9658 non-null   object
 7   Price           9659 non-null   float64
 8   Content Rating  9659 non-null   object
 9   Genres          9659 non-null   object
 10  Last Updated    9659 non-null   object
 11  Current Ver     9651 non-null   object
 12  Android Ver     9657 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 1.0+ MB

In [44]:
df_copy["Android Ver"]

0             4.0.3 and up
1             4.0.3 and up
2             4.0.3 and up
3               4.2 and up
4               4.4 and up
               ...
9655            4.1 and up
9656            4.1 and up
9657            2.2 and up
9658    Varies with device
9659    Varies with device
Name: Android Ver, Length: 9659, dtype: object